### ISSUE TITLE
Release build error on 15063

### ISSUE THREAD

**Issue by lukemcdo** [unoplatform/Uno.Core#73]
## I'm submitting a...
Regression (a behavior that used to work and stopped working in a new release)
which is also a Bug Report

## Current behavior
Uno.Core > 1.27 causes the UWP release build on SDK 15063 to fail with "Internal compiler error: Object reference not set to an instance of an object"

## Expected behavior
UWP project builds with UWP.Core.

## Minimal reproduction of the problem with instructions

1. Create a new Uno Application from the template.
2. Set minimum windows version in the UWP project head to 15063 (requires manually installing 15063 in VS 2019 from https://developer.microsoft.com/en-us/windows/downloads/sdk-archive )
3. Build the x64 release build.
4. Build fails.

## Environment
```
Nuget Package: 
Package Version(s): 2.0.0, 1.29.0, 1.28.0

Affected platform(s):
- [x] Windows

Visual Studio
- [x] 2017 (version: 15.9.27)
- [x] 2019 (version: 16.7.4)
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )
```

**Comment by jeromelaban** [comment]
Thanks for the issue.

Uno.Core is built against the 10.0.17763.0 SDK, and it's unfortunately something that we cannot change, and for which the issue is located in either the windows SDK and/or Visual Studio.

**Comment by lukemcdo** [comment]
If you don't mind -- is that 17763.0 SDK the same SDK used for 1.27?

To be clear, this isn't a pressing issue. I am able to downgrade to 1.27 in the UWP head without issue. But that prevents me from using the Hot Reload functionality, which is a tad annoying.
